name: CI
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]
jobs:
  build:
    uses: softwaremill/github-actions-workflows/.github/workflows/build-scala.yml@main
    # run on 1) push, 2) external PRs, 3) softwaremill-ci PRs
    # do not run on internal, non-steward PRs since those will be run by push to branch
    if: |
      github.event_name == 'push' || 
      github.event.pull_request.head.repo.full_name != github.repository ||
      github.event.pull_request.user.login == 'softwaremill-ci'
    strategy:
      matrix:
        java: [ '11', '17', '21' ]
      fail-fast: false
    with:
      java-version: ${{ matrix.java }}
      java-opts: '-Xmx5G --add-opens java.base/java.lang=ALL-UNNAMED'

  publish:
    uses: softwaremill/github-actions-workflows/.github/workflows/publish-release.yml@main
    needs: [build]
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
    secrets: inherit
    with:
      java-version: '17'
      java-opts: "-Xmx5G"

  label:
    # only for PRs by softwaremill-ci
    if: github.event.pull_request.user.login == 'softwaremill-ci'
    uses: softwaremill/github-actions-workflows/.github/workflows/label.yml@main

  auto-merge:
    # only for PRs by softwaremill-ci
    if: github.event.pull_request.user.login == 'softwaremill-ci'
    needs: [ build, label ]
    uses: softwaremill/github-actions-workflows/.github/workflows/auto-merge.yml@main